extraVolumes:
  - name: html
    configMap:
      name: nginx-index

extraVolumeMounts:
  - name: html
    mountPath: /app/html

serverBlockConfig: |
  location / {
    root /app/html;
    index index.html;
  }

documentRoot: /app/html

service:
  port: 80
  targetPort:
    http: 8080
    https: 8443

env:
  - name: NGINX_HTTP_PORT_NUMBER
    value: "8080"
  - name: NGINX_HTTPS_PORT_NUMBER
    value: "8443"

extraVolumes:
  - name: html
    configMap:
      name: nginx-index
  - name: server-block
    configMap:
      name: nginx-server-block

extraVolumeMounts:
  - name: html
    mountPath: /app/html
  - name: server-block
    mountPath: /opt/bitnami/nginx/conf/server_blocks/default.conf
    subPath: default.conf

resources:
  requests:
    cpu: 250m
  limits:
    cpu: 500m

